#!/bin/sh

OUT_DIR="samples"

mkdir -p $OUT_DIR



make_sample () {
	# Configure the generator
	echo unsigned int SIZE=$1\;unsigned int ITERATIONS=$2\;float POWER=$3\; > config.c
	make config

	# Generate raw data
	./mbrot-gen > $OUT_DIR/$1-$2-$3pow.raw

	# Make normal colour image
	./raw-to-png $OUT_DIR/$1-$2-$3pow.raw $1 $1
	mv 0,0.png $OUT_DIR/$1-$2.png

	# Make (hypnotic) bw image to show boundaries clearly
	./raw-to-png-bw $OUT_DIR/$1-$2-$3pow.raw $1 $1
	mv 0,0.png $OUT_DIR/$1-$2-$3-pow-bw.png

	rm $OUT_DIR/$1-$2-$3pow.raw
}

for it in 10 50 100; do
	for res in 35 70 140 280 560 1120 2240; do
		make_sample $res $it 2
	done
done
